name: Update Episode Shortlinks

on:
  workflow_dispatch:
  push:
    paths:
      - '**.json'
      - 'update_shortlinks.py'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Run update_shortlinks.py
        run: python update_shortlinks.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-update episode JSONs with shortlinks'
          
